### ISSUE TITLE
Suggestion: Bulk Upload 

### ISSUE THREAD

**Issue by lordkitsuna** [forbjok/blazebooru#1]
allow uploading multiple images under a common set of tags to facilitate inital uploading of a large set for a particular character or series for example.

**Comment by forbjok** [comment]
This is now implemented. Instead of uploading one image at a time, you can now add pretty much any number at a time (as long as it's not so many that the browser tab freezes permanently), and specify both a set of common tags that will be added to all images in that batch, as well as individual tags and properties for each image.

When upload is started, they will now be running in the background and can be viewed through an upload progress view. They will continue to run until done while you navigate around, as long as the tab is not closed or refreshed (which would cause the app to be reloaded and lose its state).
