### ISSUE TITLE
How do i change filesize limit

### ISSUE THREAD

**Issue by lordkitsuna** [forbjok/blazebooru#3]
I am trying to figure out how to increase the limit from 10MB. i have updated the nginx config to allow larger but it seems to be coded into the actual site somewhere as it will give an error message saying the image is larger than the max allowed of 10MB where can i configure this limit to be larger?

**Comment by forbjok** [comment]
Previously it wasn't really possible without editing the code, as it was just hardcoded in both the backend and frontend, but I've now made it configurable through a configuration file.

There's an example configuration at: https://github.com/forbjok/blazebooru/blob/master/backend/core/src/config/default_config.toml

This file should be called "config.toml" and be placed in a directory somewhere, and in order to use it via the docker compose setup, you can override the environment variable "BLAZEBOORU_CONFIG_PATH" with the path to that configuration directory. (NOT including the filename, just the parent directory that contains the config.toml file)

**Comment by lordkitsuna** [comment]
closed by b86f585ce1cb25a31510e689db1acddb4c96572c  :D
